---
eureka:
  client:
    serviceUrl:
      defaultZone: http://primary:8011/eureka/,http://secondary:8012/eureka/,http://tertiary:8013/eureka/
  instance:
    prefer-ip-address: true
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.
spring:
  cloud:
    config:
      fail-fast: true
